AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for scheduled Lambda with S3 write permissions

Parameters:
  RssUrl:
    Type: String
    Description: URL of the RSS feed to fetch

  S3BucketName:
    Type: String
    Description: Name of the S3 bucket where RSS feed will be stored

  S3KeyName:
    Type: String
    Description: Key (file path) where the RSS feed will be stored in S3

Resources:
  ScheduledLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-scheduled-lambda-function
      Handler: sumiya.rss.RssToS3Lambda::handleRequest
      Runtime: java21
      Architectures:
        - arm64
      CodeUri: ../build/distributions/rss-to-s3-1.0-SNAPSHOT.zip
      MemorySize: 512
      Timeout: 30
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          RSS_URL: !Ref RssUrl
          S3_DESTINATION_BUCKET: !Ref S3BucketName
          S3_DESTINATION_KEY: !Ref S3KeyName
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Name: !Sub ${AWS::StackName}-DailySchedule
            Description: Triggers lambda function daily
            Enabled: true
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3BucketName

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ScheduledLambdaFunction}
      RetentionInDays: 30

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ScheduledLambdaFunction.Arn
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref ScheduledLambdaFunction